[workspace]
members = ["demos/quinn_h3", "demos/quiche"]
exclude = [".work"]
resolver = "2"

[workspace.dependencies]
js-sys = { path = ".work/wasm-bindgen/crates/js-sys" }
wasm-bindgen = { path = ".work/wasm-bindgen" }
wasm-bindgen-futures = { path = ".work/wasm-bindgen/crates/futures" }

[patch.crates-io]
datagram-socket = { path = ".work/quiche-tokio/datagram-socket" }
js-sys = { path = ".work/wasm-bindgen/crates/js-sys" }
wasm-bindgen = { path = ".work/wasm-bindgen" }
wasm-bindgen-futures = { path = ".work/wasm-bindgen/crates/futures" }
wasm-bindgen-macro-support = { path = ".work/wasm-bindgen/crates/macro-support" }
wasm-bindgen-shared = { path = ".work/wasm-bindgen/crates/shared" }
libc = { path = ".work/libc" }
mio = { git = "https://github.com/guybedford/mio", rev = "4c43fd5522f5b13a5bc2d4b54bd7f50e698084d1" }
octets = { path = ".work/quiche-tokio/octets" }
qlog = { path = ".work/quiche-tokio/qlog" }
quanta = { path = ".work/quanta" }
quiche = { path = ".work/quiche-tokio/quiche" }
ring = { path = ".work/ring" }
socket2 = { git = "https://github.com/rust-lang/socket2", rev = "239dd83a4ced08e514d2c38942aab99791119f0d" }
tokio = { path = ".work/tokio/tokio" }
tokio-macros = { path = ".work/tokio/tokio-macros" }

[patch."https://github.com/guybedford/libc"]
libc = { path = ".work/libc" }

[profile.release]
opt-level = "s"
